Repository deprecation notice
Esri/resource-proxy pull request #562
Opened 2021-08-04 23:19 UTC by andygup

This PR supersedes https://github.com/Esri/resource-proxy/pull/556. It includes updates to place the repository in deprecation mode.

Browser and web server technology has advanced since this repo was originally created, and there are significantly better ways to manage secure geospatial services today. Some examples are documented in the README, such as CORS, API keys, as well as the ability provide fine-grained access management and secure services through ArcGIS Online and ArcGIS Enterprise.

2022-08-05 14:08 UTC, andygup commented
Bump

2023-02-08 23:53 UTC, bsvensson requested changes
As part of deprecation, I think we can also remove the SUPPORT.md.

2023-02-09 17:44 UTC, andygup commented
@bsvensson updates completed.

2023-02-23 18:31 UTC, bsvensson approved these changes

2023-02-23 19:18 UTC, merged